name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: mkdir -p data  

      - run: npx prisma generate

      - run: npm run build

      # 🔐 Connexion au registre GitHub
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🐳 Build et push de l'image
      - name: Build & Push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/task-manager-noufou:latest .
          docker push ghcr.io/${{ github.repository_owner }}/task-manager-noufou:latest
          